# Generated by Django 2.2.6 on 2020-04-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mall_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('order_no', models.BigIntegerField(verbose_name='订单号')),
                ('product_id', models.IntegerField(verbose_name='商品id')),
                ('address_id', models.IntegerField(verbose_name='地址id')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='实付价格（元）')),
                ('payment_type', models.IntegerField(choices=[(0, '在线支付'), (1, '货到付款')], verbose_name='支付类型，比如在线支付')),
                ('status', models.IntegerField(choices=[(0, '已取消'), (1, '未付款'), (2, '已付款'), (3, '已发货'), (4, '交易成功'), (5, '交易关闭')], verbose_name='订单状态')),
                ('payment_time', models.DateTimeField(blank=True, verbose_name='支付时间')),
                ('send_time', models.DateTimeField(blank=True, verbose_name='发货时间')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='交易完成时间')),
                ('close_time', models.DateTimeField(blank=True, verbose_name='交易关闭时间')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mall_order',
            },
        ),
        migrations.CreateModel(
            name='mall_pay_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('order_no', models.BigIntegerField(verbose_name='订单号')),
                ('payment_platform', models.IntegerField(choices=[(0, '支付宝'), (1, '微信')], verbose_name='支付平台')),
                ('platform_number', models.CharField(max_length=50, verbose_name='支付流水号')),
                ('platform_status', models.CharField(max_length=30, verbose_name='支付状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mall_pay_info',
            },
        ),
        migrations.AddIndex(
            model_name='mall_order',
            index=models.Index(fields=['order_no'], name='order_idx'),
        ),
        migrations.AddIndex(
            model_name='mall_order',
            index=models.Index(fields=['user_id', 'order_no'], name='user_id_order_no_idx'),
        ),
    ]
