# Generated by Django 2.2.6 on 2020-04-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall_order',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='交易关闭时间'),
        ),
        migrations.AlterField(
            model_name='mall_order',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='交易完成时间'),
        ),
        migrations.AlterField(
            model_name='mall_order',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AlterField(
            model_name='mall_order',
            name='send_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发货时间'),
        ),
    ]
