# Generated by Django 2.2.6 on 2020-04-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mall_product_auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='品牌')),
                ('brand_sub', models.CharField(default='无', max_length=20, verbose_name='子品牌')),
                ('model', models.CharField(max_length=20, verbose_name='型号')),
                ('detail', models.TextField(verbose_name='商品的描述')),
                ('first_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='首拍价格')),
                ('late_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='当前的价格')),
                ('main_image', models.CharField(max_length=30, verbose_name='展示框的图片')),
                ('sub_image', models.TextField(verbose_name='更多图片')),
                ('status', models.IntegerField(choices=[(0, '在售'), (1, '已售'), (2, '下架'), (3, '删除')], verbose_name='商品的状态')),
                ('user_id_seller', models.IntegerField(verbose_name='卖家id')),
                ('user_id_consumer', models.IntegerField(blank=True, null=True, verbose_name='买家id')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mall_product_auction',
            },
        ),
        migrations.CreateModel(
            name='mall_product_normal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='品牌')),
                ('brand_sub', models.CharField(default='无', max_length=20, verbose_name='子品牌')),
                ('model', models.CharField(max_length=20, verbose_name='型号')),
                ('detail', models.TextField(verbose_name='商品的描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('main_image', models.CharField(max_length=30, verbose_name='展示框的图片')),
                ('sub_image', models.TextField(verbose_name='更多图片')),
                ('status', models.IntegerField(choices=[(0, '已售'), (1, '在售'), (2, '下架'), (3, '删除')], default=1, verbose_name='商品的状态')),
                ('user_id_seller', models.IntegerField(verbose_name='卖家id')),
                ('user_id_consumer', models.IntegerField(blank=True, verbose_name='买家id')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mall_product_normal',
            },
        ),
        migrations.AddIndex(
            model_name='mall_product_normal',
            index=models.Index(fields=['brand', 'model', 'price'], name='brand_model_price_idx'),
        ),
        migrations.AddIndex(
            model_name='mall_product_normal',
            index=models.Index(fields=['user_id_seller'], name='user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='mall_product_auction',
            index=models.Index(fields=['brand', 'model', 'late_price'], name='brand_model_price_idx'),
        ),
        migrations.AddIndex(
            model_name='mall_product_auction',
            index=models.Index(fields=['user_id_seller'], name='user_id_idx'),
        ),
    ]
