# Generated by Django 2.2.6 on 2020-04-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mall_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分裂名称')),
            ],
            options={
                'db_table': 'mall_category',
            },
        ),
        migrations.CreateModel(
            name='mall_goods_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, verbose_name='品牌')),
                ('model', models.CharField(max_length=40, verbose_name='型号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='参考价格')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mall_goods_info',
            },
        ),
        migrations.AddIndex(
            model_name='mall_goods_info',
            index=models.Index(fields=['model'], name='model_idx'),
        ),
    ]
