# Generated by Django 2.2.6 on 2020-04-14 08:59

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='mall_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名，唯一')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('alipay_id', models.CharField(blank=True, max_length=30, verbose_name='支付宝用户号')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '注销'), (3, '异常')], default=1, verbose_name='用户状态')),
                ('role', models.IntegerField(choices=[(1, '普通用户'), (2, '管理员')], default=1, verbose_name='用户身份')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mall_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='mall_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('name', models.CharField(max_length=20, verbose_name='收获姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='收获电话')),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20, verbose_name='区/县')),
                ('detail_address', models.CharField(max_length=30, verbose_name='详细地址')),
                ('zip_number', models.CharField(default='000000', max_length=20, verbose_name='邮编')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mall_address',
            },
        ),
        migrations.CreateModel(
            name='mall_collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('product_id', models.IntegerField(verbose_name='商品id')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mall_collect',
            },
        ),
        migrations.AddIndex(
            model_name='mall_collect',
            index=models.Index(fields=['user_id'], name='user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='mall_address',
            index=models.Index(fields=['user_id'], name='user_id_idx'),
        ),
        migrations.AddField(
            model_name='mall_user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='mall_user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='mall_user',
            index=models.Index(fields=['username'], name='username_unique'),
        ),
    ]
